### ISSUE TITLE
Large display for editing and active time

### ISSUE THREAD

**Issue by tiritto** [EyeOdin/timer_watch#1]
Hello there!

I wonder if it would be possible to implement Active Time and Editing Time watcher as new possible options in dropdown menu?

I am fully aware that both of those values can be found under Information option, but I think it would be nice to be able to select those individual values and display them in the same fashion as Stopwatch and Clock are displayed - with large clear digits, and without any additional information clutter.

**Comment by EyeOdin** [comment]
Currently that idea is not possible through the API the only alternative is to create a hack that creates lag to the system and makes the Krita interface buggy when using multiple views or even swapping between documents or krita instances.

I already made a  Feature request to Krita developers for such a feature as it would help control time spent of the user and enable to guess when is the best time to make a heavier update without causing too much troubles. No one seems interested in such.

Currently you can only read the edit time from save files and it is there from where I read it. I just expose it and make it reading more humanly readable.
